name: astronerf
channels:
    - conda-forge
    - pytorch
dependencies:
    - astropy
    - easydict
    - gdown
    - imageio
    - ipdb
    - matplotlib
    - numpy
    - Pillow
    - pip
    - pytorch>=1.9.0
    - pyyaml
    - scikit-video
    - scipy
    - termcolor
    - tqdm
    - torchvision
    - trimesh
    - setuptools=59.5.0
    - pip:
      - lpips
      - artpop