group: planet                                         # name of experiment group
name: 0                                                # name of experiment run
seed: 3                                                     # seed number (for both numpy and pytorch)
yaml: 
cpu: False
gpu: 0

data:                                                       # data options
    root:                                                   # root path to dataset
    dataset:                                           # dataset name
    image_size: [338,600]                                   # original image size
    patch_crop: [250,500]

optim:                                                      # optimization options
    lr: 1.e-4                                              # learning rate (main)
    lr_warp: 1.e-4                                      # learning rate of warp parameters
    algo: Adam                                              # optimizer (see PyTorch doc)                                         
    sched:                                                  # learning rate scheduling options
        #type: StepLR                                  # scheduler (see PyTorch doc)                             # decay every N epochs
        #max_lr: 0.1
        #type: StepLR                                        # scheduler (see PyTorch doc)
        #step_size: 1000
        #gamma: 0.1

output_root:                                          # root path for output files (checkpoints and results)

freq:                                                       # periodic actions during training
    scalar: 200                                             # log losses and scalar states (every N iteration

arch:                                                       # architectural options
    layers: [null,256,256,256,256,3]                        # hidden layers for MLP
    skip: []                                                # skip connections
    posenc:                                                 # positional encoding
        L_2D: 8                                             # number of bases (3D point)

barf_c2f: [0.1,0.5]                                                  # coarse-to-fine scheduling on positional encoding

warp:  
    dof: 8                                                  # image warping options
    noise_h: 0.1                                            # scale of pre-generated warp perturbation (homography)
    noise_t: 0.4                                           # scale of pre-generated warp perturbation (translation)
    fix_first: true                                         # fix the first patch for uniqueness of solution

loss_weight:                                                # loss weights (in log scale)
    render: 0                                               # RGB rendering loss

batch_size: 9                                               # batch size (set to number of images in dataset)
max_iter: 5000                                              # train to maximum number of iterations
loss_type: l1                                              # 'mse' or 'l1'